spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.57.14:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
logging:
  level:
    root: info
    com.lhhh: debug
  file:
    name: log/blog.txt

server:
  port: 18080
#驼峰命名映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Dao.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
